{% set name = "sanic-cors" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Sanic-Cors-{{ version }}.tar.gz
  sha256: 4d2f26333d49db428217814c66e89fc3df20fc62a5ab518a71fa22e2e249e19d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sanic >=18.12.0
    - sanic-plugins-framework >=0.9.0

test:
  imports:
    - sanic_cors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashleysommer/sanic-cors
  summary: A Sanic extension adding a decorator for CORS support. Based on flask-cors by Cory Dolphin.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - patricksnape
