{% set name = "sanic-cors" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Sanic-Cors-{{ version }}.tar.gz
  sha256: d6109b342afcaa053db663d92d44f4f61e59cdb0d0a3c1857dcc9812a6595a61

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sanic >=18.12.0
    - sanic-plugins-framework >=0.9.0

test:
  imports:
    - sanic_cors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ashleysommer/sanic-cors
  summary: A Sanic extension adding a decorator for CORS support. Based on flask-cors by Cory Dolphin.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - patricksnape
