{% set version = "2.2.0" %}

package:
  name: sanic-cors
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/sanic-cors/Sanic-Cors-{{ version }}.tar.gz
  sha256: f8d7515da4c8b837871d422c66314c4b5704396a78894b59c50e26aa72a95873

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - packaging >=21.3
    - python >=3.7
    - sanic >=21.9.3

test:
  requires:
    - pip
  imports:
    - sanic_cors
  commands:
    - pip check

about:
  home: https://github.com/ashleysommer/sanic-cors
  summary: A Sanic extension adding a decorator for CORS support. Based on flask-cors by Cory Dolphin.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - patricksnape
    - bollwyvl
